name: My Workflow parametrized 

on:
push:
branches: [main]

jobs:
my-job:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2
- name: Build and test
run: |
npm install
npm run build
npm test

jobs:
my-job:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2
- name: Build and test
run: |
npm install
npm run build
npm test
with:
node-version: '14.x'
env: |
API_KEY=${{ secrets.API_KEY }}
DATABASE_URL=${{ secrets.DATABASE_URL }}
